# Base Image
FROM node:18
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package*.json ./
# Install dependencies
RUN npm install
# Bundle app source
COPY . .
#Expose port to 3000
EXPOSE 3000
# Add command to run
CMD [ "npm", "start" ]
